train:
  training:
    device: cuda
    gpu:
      enabled: true
      visible_devices: "0"
      max_num_gpus: 1
      memory_fraction: 0.70
      allow_tf32: true
      cudnn_benchmark: false
      empty_cache_on_start: true
      log_gpu_info: true
      fail_if_cuda_unavailable: false

  dataset:
    repo_id: "dual_franka2_test/single_arm_pick_20260519_merged"
    root: "/home/deepcybo/.cache/huggingface/lerobot/dual_franka2_test/single_arm_pick_20260519_merged"

  env:

  policy:
    type: "act"  # act | diffusion
    device: "cuda"
    use_amp: true
    repo_id: "shenzhaolong/act_policy"
    push_to_hub: false
    temporal_ensemble_coeff: 0.03
    chunk_size: 20
    n_action_steps: 1
    # pretrained_path:

  output_dir: "outputs/train/dual_franka2_test/single_arm_pick/act_20260519_E50_V01"
  job_name: "act_policy_dual_franka2_test_single_arm_pick_20260519_E50_V01"

  resume: false
  seed: 1000
  # Number of workers for the dataloader.
  num_workers: 4
  batch_size: 16
  steps: 40_000
  eval_freq: 20_00
  log_freq: 200
  save_checkpoint: true
  save_freq: 20_00
  use_policy_training_preset: true

  eval:
    n_episodes: 10
    batch_size: 8

  wandb:
    enable: true
    project: "lerobot_franka"
    mode: "online"
