train:
  dataset:
    repo_id: "nero_task3_step1/8mL_empty_left_merged_20260508_E125" # HuggingFace 数据集 repo_id，格式为 "username/dataset_name"
  # 指向包含数据集 repo 的本地目录（要包含 repo_id 子目录），
  # 例如本地缓存路径下的 physbrain3/pick_and_place_merged
    root: "/home/deepcybo/.cache/huggingface/lerobot/nero_task3_step1/8mL_empty_left_merged_20260508_E125"

  env:

  policy:
    # 推荐保持为普通 ACT；轮次式 DAgger 会由 run_dagger_rounds.py 在内存中注入训练参数。
    type: "act"
    device: "cuda"
    repo_id: "shenzhaolong/act_policy"
    push_to_hub: false  # 禁用模型推送
    # temporal_ensemble_coeff: null # 关闭时序加权，减少动作启动迟滞
    chunk_size: 30
    n_action_steps: 5
    
    # === 可暴露/调整的超参数配置 (针对 Diffusion 策略可覆盖) ===
    # horizon: 16                # [Diffusion] 扩散模型的预测窗口长度 (即 Chunk size)
    # n_obs_steps: 2             # [Diffusion] 观察步数记录历史
    # num_inference_steps: 100   # [Diffusion] 实际预测推理的降噪步数 (变小降低延迟如 10)
    # optimizer_lr: 0.0001       # 学习率 (不提供则按库的默认值: Diffusion: 1e-4, ACT: 1e-5)

    # pretrained_path: "/home/deepcybo/wbcd_ws/Le-nero/dual_arm_data_collection/lerobot_dual_arm_teleop/outputs/train\
    #                   /task3_step1/8mL_empty_left/[worked]act_20260508_E125/checkpoints/010000/pretrained_model"  # 从 ACT checkpoint 继续训练

  output_dir: "/home/deepcybo/wbcd_ws/Le-nero/dual_arm_data_collection/lerobot_dual_arm_teleop/outputs/train\
              /task3_step1/8mL_empty_left/act_20260513_E125_test" # 模型和日志的输出目录
  job_name: "8mL_empty_left_act_20260513_E125_test"

  resume: false
  seed: 1000
  # Number of workers for the dataloader.
  num_workers: 4
  batch_size: 32
  steps: 10_000
  eval_freq: 20_00
  log_freq: 200
  save_checkpoint: True
  # Checkpoint is saved every `save_freq` training iterations and after the last training step.
  save_freq: 5_000
  use_policy_training_preset: True

  eval: 
    n_episodes: 10
    batch_size: 8

  wandb: 
    enable: False
    project: "lerobot_nero"
    # entity: "your-wandb-username"  # 改为您的 WandB 用户名，或注释掉使用默认
    # notes: "训练备注"
    # run_id: "自定义运行ID"
    mode: "online"  # Allowed values: 'online', 'offline' 'disabled'. Defaults to 'online"
